const userAttribute = [
  'ID',
  'first_name',
  'last_name',
  'username',
  'email',
  'password',
  'age',
  'gender',
  'Net worth',
  'Net investible assets',
  'Liabilities',
  'Yearly Income',
  'Target Retirement Age',
  'Lifestyle (Expenditure per month)',
  'Experience in investments (1 lowest, 4 aggressive/strong)',
  'Investment Objectives (1 lowest, 4 aggressive/strong)',
  'Losses willing to tolerate in market crash',
  'Market Fluctuation willing to tolerate',
  'Time Commitment',
  'What do you do during downturn',
  'Short Term Needs (0-3yr)',
  'Medium Term Needs (5-10yr)',
  'Long Term Needs (15-20yr)',
  "Customer's investment news counter history #1",
  "Customer's investment news counter history #2",
  "Customer's investment news counter history #3",
  "Customer's investment news counter history #4",
  "Customer's investment news sector history",
  "Customer's investment news industry history",
  "Customer's investment history #1",
  "Customer's investment history #2",
  "Customer's investment history #3",
  "Customer's investment history #4",
  "Customer's investment history #5",
  "Customer's investment history #6",
  "Customer's investment history #7",
  "Customer's investment history #8",
  "Customer's investment history #9",
  "Customer's investment history #10",
  "DOB",
  "Customer's investment history #0"
]

module.exports = userAttribute
